### PR TITLE
rewrite 0.9

### PR DESCRIPTION
**Pull request by shukari**
- now smaller & compacter scripts
- more to separate functions
- compacter modules
- fix for eden module reassignto buildings after UNDO
- modules now use config values
- two interior scripts to one
- split the templates out of the script
- allow custom buildings templates from mission makers (ZEI_civ_customBuildings & ZEI_mil_customBuildings)
- new module for easier creating a template/scheme without any code execute stuff
- little optimizations
- modules names are now more consistent
- now the mod also supports buildings not only houses
- the mod now allow also interiors for buildings without AI positions (experimental)
- optimized the template generator (block CuratorCam)
- some stuff i dont remember

### CODE REVIEW

**Comment by shukari** [comment]
@LISTINGS09 please give this PR a short look ^^

**Comment by LISTINGS09** [comment]
Many thanks for taking the time to update this, will take a look!

**Comment by shukari** [comment]
Now support of modded scheme capture (CUP...) and selecting only working schemes for spawning.

**Review by LISTINGS09 — APPROVED** [review]
Awesome stuff - Thanks!

**Pull request merged**
